#############################################################################
# Makefile for building: newPhonon
# Generated by qmake (2.01a) (Qt 4.8.2) on: sam. janv. 12 16:11:34 2013
# Project:  newPhonon.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile newPhonon.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_WEBKIT_LIB -DQT_PHONON_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/phonon -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I/usr/local/include -I/usr/include/qt4/phonon_compat -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/local/lib/ -ltag -lQtWebKit -lphonon -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		cutesong.cpp \
		classSQL.cpp \
		song.cpp \
		playlist.cpp \
		newplaylistdialog.cpp \
		existingplaylistdialog.cpp \
		renameplaylistdialog.cpp \
		tageditiondialog.cpp \
		importexport.cpp \
		existingplaylistimportdialog.cpp moc_cutesong.cpp \
		moc_newplaylistdialog.cpp \
		moc_existingplaylistdialog.cpp \
		moc_renameplaylistdialog.cpp \
		moc_tageditiondialog.cpp \
		moc_existingplaylistimportdialog.cpp
OBJECTS       = main.o \
		cutesong.o \
		classSQL.o \
		song.o \
		playlist.o \
		newplaylistdialog.o \
		existingplaylistdialog.o \
		renameplaylistdialog.o \
		tageditiondialog.o \
		importexport.o \
		existingplaylistimportdialog.o \
		moc_cutesong.o \
		moc_newplaylistdialog.o \
		moc_existingplaylistdialog.o \
		moc_renameplaylistdialog.o \
		moc_tageditiondialog.o \
		moc_existingplaylistimportdialog.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		newPhonon.pro
QMAKE_TARGET  = newPhonon
DESTDIR       = 
TARGET        = newPhonon

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_cutesong.h ui_newplaylistdialog.h ui_existingplaylistdialog.h ui_renameplaylistdialog.h ui_tageditiondialog.h ui_existingplaylistimportdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: newPhonon.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtWebKit.prl \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile newPhonon.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtWebKit.prl:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile newPhonon.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/newPhonon1.0.0 || $(MKDIR) .tmp/newPhonon1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/newPhonon1.0.0/ && $(COPY_FILE) --parents cutesong.h classSQL.h song.h playlist.h newplaylistdialog.h existingplaylistdialog.h renameplaylistdialog.h tageditiondialog.h importexport.h existingplaylistimportdialog.h .tmp/newPhonon1.0.0/ && $(COPY_FILE) --parents main.cpp cutesong.cpp classSQL.cpp song.cpp playlist.cpp newplaylistdialog.cpp existingplaylistdialog.cpp renameplaylistdialog.cpp tageditiondialog.cpp importexport.cpp existingplaylistimportdialog.cpp .tmp/newPhonon1.0.0/ && $(COPY_FILE) --parents cutesong.ui newplaylistdialog.ui existingplaylistdialog.ui renameplaylistdialog.ui tageditiondialog.ui existingplaylistimportdialog.ui .tmp/newPhonon1.0.0/ && (cd `dirname .tmp/newPhonon1.0.0` && $(TAR) newPhonon1.0.0.tar newPhonon1.0.0 && $(COMPRESS) newPhonon1.0.0.tar) && $(MOVE) `dirname .tmp/newPhonon1.0.0`/newPhonon1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/newPhonon1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_cutesong.cpp moc_newplaylistdialog.cpp moc_existingplaylistdialog.cpp moc_renameplaylistdialog.cpp moc_tageditiondialog.cpp moc_existingplaylistimportdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cutesong.cpp moc_newplaylistdialog.cpp moc_existingplaylistdialog.cpp moc_renameplaylistdialog.cpp moc_tageditiondialog.cpp moc_existingplaylistimportdialog.cpp
moc_cutesong.cpp: classSQL.h \
		song.h \
		/usr/local/include/taglib/id3v2tag.h \
		/usr/local/include/taglib/tag.h \
		/usr/local/include/taglib/taglib_export.h \
		/usr/local/include/taglib/taglib_config.h \
		/usr/local/include/taglib/tstring.h \
		/usr/local/include/taglib/taglib.h \
		/usr/local/include/taglib/tbytevector.h \
		/usr/local/include/taglib/tlist.h \
		/usr/local/include/taglib/tlist.tcc \
		/usr/local/include/taglib/tmap.h \
		/usr/local/include/taglib/tmap.tcc \
		/usr/local/include/taglib/id3v2framefactory.h \
		/usr/local/include/taglib/id3v2frame.h \
		/usr/local/include/taglib/id3v2header.h \
		/usr/local/include/taglib/mpegfile.h \
		/usr/local/include/taglib/tfile.h \
		/usr/local/include/taglib/tiostream.h \
		/usr/local/include/taglib/mpegproperties.h \
		/usr/local/include/taglib/audioproperties.h \
		/usr/local/include/taglib/mpegheader.h \
		/usr/local/include/taglib/attachedpictureframe.h \
		cutesong.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cutesong.h -o moc_cutesong.cpp

moc_newplaylistdialog.cpp: newplaylistdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) newplaylistdialog.h -o moc_newplaylistdialog.cpp

moc_existingplaylistdialog.cpp: existingplaylistdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) existingplaylistdialog.h -o moc_existingplaylistdialog.cpp

moc_renameplaylistdialog.cpp: renameplaylistdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) renameplaylistdialog.h -o moc_renameplaylistdialog.cpp

moc_tageditiondialog.cpp: /usr/local/include/taglib/fileref.h \
		/usr/local/include/taglib/tfile.h \
		/usr/local/include/taglib/taglib_export.h \
		/usr/local/include/taglib/taglib_config.h \
		/usr/local/include/taglib/taglib.h \
		/usr/local/include/taglib/tag.h \
		/usr/local/include/taglib/tstring.h \
		/usr/local/include/taglib/tbytevector.h \
		/usr/local/include/taglib/tiostream.h \
		/usr/local/include/taglib/tstringlist.h \
		/usr/local/include/taglib/tlist.h \
		/usr/local/include/taglib/tlist.tcc \
		/usr/local/include/taglib/tbytevectorlist.h \
		/usr/local/include/taglib/audioproperties.h \
		tageditiondialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tageditiondialog.h -o moc_tageditiondialog.cpp

moc_existingplaylistimportdialog.cpp: existingplaylistimportdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) existingplaylistimportdialog.h -o moc_existingplaylistimportdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_cutesong.h ui_newplaylistdialog.h ui_existingplaylistdialog.h ui_renameplaylistdialog.h ui_tageditiondialog.h ui_existingplaylistimportdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_cutesong.h ui_newplaylistdialog.h ui_existingplaylistdialog.h ui_renameplaylistdialog.h ui_tageditiondialog.h ui_existingplaylistimportdialog.h
ui_cutesong.h: cutesong.ui
	/usr/bin/uic-qt4 cutesong.ui -o ui_cutesong.h

ui_newplaylistdialog.h: newplaylistdialog.ui
	/usr/bin/uic-qt4 newplaylistdialog.ui -o ui_newplaylistdialog.h

ui_existingplaylistdialog.h: existingplaylistdialog.ui
	/usr/bin/uic-qt4 existingplaylistdialog.ui -o ui_existingplaylistdialog.h

ui_renameplaylistdialog.h: renameplaylistdialog.ui
	/usr/bin/uic-qt4 renameplaylistdialog.ui -o ui_renameplaylistdialog.h

ui_tageditiondialog.h: tageditiondialog.ui
	/usr/bin/uic-qt4 tageditiondialog.ui -o ui_tageditiondialog.h

ui_existingplaylistimportdialog.h: existingplaylistimportdialog.ui
	/usr/bin/uic-qt4 existingplaylistimportdialog.ui -o ui_existingplaylistimportdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp cutesong.h \
		classSQL.h \
		song.h \
		/usr/local/include/taglib/id3v2tag.h \
		/usr/local/include/taglib/tag.h \
		/usr/local/include/taglib/taglib_export.h \
		/usr/local/include/taglib/taglib_config.h \
		/usr/local/include/taglib/tstring.h \
		/usr/local/include/taglib/taglib.h \
		/usr/local/include/taglib/tbytevector.h \
		/usr/local/include/taglib/tlist.h \
		/usr/local/include/taglib/tlist.tcc \
		/usr/local/include/taglib/tmap.h \
		/usr/local/include/taglib/tmap.tcc \
		/usr/local/include/taglib/id3v2framefactory.h \
		/usr/local/include/taglib/id3v2frame.h \
		/usr/local/include/taglib/id3v2header.h \
		/usr/local/include/taglib/mpegfile.h \
		/usr/local/include/taglib/tfile.h \
		/usr/local/include/taglib/tiostream.h \
		/usr/local/include/taglib/mpegproperties.h \
		/usr/local/include/taglib/audioproperties.h \
		/usr/local/include/taglib/mpegheader.h \
		/usr/local/include/taglib/attachedpictureframe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cutesong.o: cutesong.cpp cutesong.h \
		classSQL.h \
		song.h \
		/usr/local/include/taglib/id3v2tag.h \
		/usr/local/include/taglib/tag.h \
		/usr/local/include/taglib/taglib_export.h \
		/usr/local/include/taglib/taglib_config.h \
		/usr/local/include/taglib/tstring.h \
		/usr/local/include/taglib/taglib.h \
		/usr/local/include/taglib/tbytevector.h \
		/usr/local/include/taglib/tlist.h \
		/usr/local/include/taglib/tlist.tcc \
		/usr/local/include/taglib/tmap.h \
		/usr/local/include/taglib/tmap.tcc \
		/usr/local/include/taglib/id3v2framefactory.h \
		/usr/local/include/taglib/id3v2frame.h \
		/usr/local/include/taglib/id3v2header.h \
		/usr/local/include/taglib/mpegfile.h \
		/usr/local/include/taglib/tfile.h \
		/usr/local/include/taglib/tiostream.h \
		/usr/local/include/taglib/mpegproperties.h \
		/usr/local/include/taglib/audioproperties.h \
		/usr/local/include/taglib/mpegheader.h \
		/usr/local/include/taglib/attachedpictureframe.h \
		ui_cutesong.h \
		playlist.h \
		newplaylistdialog.h \
		existingplaylistdialog.h \
		existingplaylistimportdialog.h \
		renameplaylistdialog.h \
		tageditiondialog.h \
		/usr/local/include/taglib/fileref.h \
		/usr/local/include/taglib/tstringlist.h \
		/usr/local/include/taglib/tbytevectorlist.h \
		importexport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cutesong.o cutesong.cpp

classSQL.o: classSQL.cpp classSQL.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classSQL.o classSQL.cpp

song.o: song.cpp song.h \
		/usr/local/include/taglib/id3v2tag.h \
		/usr/local/include/taglib/tag.h \
		/usr/local/include/taglib/taglib_export.h \
		/usr/local/include/taglib/taglib_config.h \
		/usr/local/include/taglib/tstring.h \
		/usr/local/include/taglib/taglib.h \
		/usr/local/include/taglib/tbytevector.h \
		/usr/local/include/taglib/tlist.h \
		/usr/local/include/taglib/tlist.tcc \
		/usr/local/include/taglib/tmap.h \
		/usr/local/include/taglib/tmap.tcc \
		/usr/local/include/taglib/id3v2framefactory.h \
		/usr/local/include/taglib/id3v2frame.h \
		/usr/local/include/taglib/id3v2header.h \
		/usr/local/include/taglib/mpegfile.h \
		/usr/local/include/taglib/tfile.h \
		/usr/local/include/taglib/tiostream.h \
		/usr/local/include/taglib/mpegproperties.h \
		/usr/local/include/taglib/audioproperties.h \
		/usr/local/include/taglib/mpegheader.h \
		/usr/local/include/taglib/attachedpictureframe.h \
		/usr/local/include/taglib/fileref.h \
		/usr/local/include/taglib/tstringlist.h \
		/usr/local/include/taglib/tbytevectorlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o song.o song.cpp

playlist.o: playlist.cpp playlist.h \
		song.h \
		/usr/local/include/taglib/id3v2tag.h \
		/usr/local/include/taglib/tag.h \
		/usr/local/include/taglib/taglib_export.h \
		/usr/local/include/taglib/taglib_config.h \
		/usr/local/include/taglib/tstring.h \
		/usr/local/include/taglib/taglib.h \
		/usr/local/include/taglib/tbytevector.h \
		/usr/local/include/taglib/tlist.h \
		/usr/local/include/taglib/tlist.tcc \
		/usr/local/include/taglib/tmap.h \
		/usr/local/include/taglib/tmap.tcc \
		/usr/local/include/taglib/id3v2framefactory.h \
		/usr/local/include/taglib/id3v2frame.h \
		/usr/local/include/taglib/id3v2header.h \
		/usr/local/include/taglib/mpegfile.h \
		/usr/local/include/taglib/tfile.h \
		/usr/local/include/taglib/tiostream.h \
		/usr/local/include/taglib/mpegproperties.h \
		/usr/local/include/taglib/audioproperties.h \
		/usr/local/include/taglib/mpegheader.h \
		/usr/local/include/taglib/attachedpictureframe.h \
		classSQL.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playlist.o playlist.cpp

newplaylistdialog.o: newplaylistdialog.cpp newplaylistdialog.h \
		ui_newplaylistdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newplaylistdialog.o newplaylistdialog.cpp

existingplaylistdialog.o: existingplaylistdialog.cpp existingplaylistdialog.h \
		ui_existingplaylistdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o existingplaylistdialog.o existingplaylistdialog.cpp

renameplaylistdialog.o: renameplaylistdialog.cpp renameplaylistdialog.h \
		ui_renameplaylistdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renameplaylistdialog.o renameplaylistdialog.cpp

tageditiondialog.o: tageditiondialog.cpp tageditiondialog.h \
		/usr/local/include/taglib/fileref.h \
		/usr/local/include/taglib/tfile.h \
		/usr/local/include/taglib/taglib_export.h \
		/usr/local/include/taglib/taglib_config.h \
		/usr/local/include/taglib/taglib.h \
		/usr/local/include/taglib/tag.h \
		/usr/local/include/taglib/tstring.h \
		/usr/local/include/taglib/tbytevector.h \
		/usr/local/include/taglib/tiostream.h \
		/usr/local/include/taglib/tstringlist.h \
		/usr/local/include/taglib/tlist.h \
		/usr/local/include/taglib/tlist.tcc \
		/usr/local/include/taglib/tbytevectorlist.h \
		/usr/local/include/taglib/audioproperties.h \
		ui_tageditiondialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tageditiondialog.o tageditiondialog.cpp

importexport.o: importexport.cpp importexport.h \
		playlist.h \
		song.h \
		/usr/local/include/taglib/id3v2tag.h \
		/usr/local/include/taglib/tag.h \
		/usr/local/include/taglib/taglib_export.h \
		/usr/local/include/taglib/taglib_config.h \
		/usr/local/include/taglib/tstring.h \
		/usr/local/include/taglib/taglib.h \
		/usr/local/include/taglib/tbytevector.h \
		/usr/local/include/taglib/tlist.h \
		/usr/local/include/taglib/tlist.tcc \
		/usr/local/include/taglib/tmap.h \
		/usr/local/include/taglib/tmap.tcc \
		/usr/local/include/taglib/id3v2framefactory.h \
		/usr/local/include/taglib/id3v2frame.h \
		/usr/local/include/taglib/id3v2header.h \
		/usr/local/include/taglib/mpegfile.h \
		/usr/local/include/taglib/tfile.h \
		/usr/local/include/taglib/tiostream.h \
		/usr/local/include/taglib/mpegproperties.h \
		/usr/local/include/taglib/audioproperties.h \
		/usr/local/include/taglib/mpegheader.h \
		/usr/local/include/taglib/attachedpictureframe.h \
		classSQL.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o importexport.o importexport.cpp

existingplaylistimportdialog.o: existingplaylistimportdialog.cpp existingplaylistimportdialog.h \
		ui_existingplaylistimportdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o existingplaylistimportdialog.o existingplaylistimportdialog.cpp

moc_cutesong.o: moc_cutesong.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cutesong.o moc_cutesong.cpp

moc_newplaylistdialog.o: moc_newplaylistdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newplaylistdialog.o moc_newplaylistdialog.cpp

moc_existingplaylistdialog.o: moc_existingplaylistdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_existingplaylistdialog.o moc_existingplaylistdialog.cpp

moc_renameplaylistdialog.o: moc_renameplaylistdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_renameplaylistdialog.o moc_renameplaylistdialog.cpp

moc_tageditiondialog.o: moc_tageditiondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tageditiondialog.o moc_tageditiondialog.cpp

moc_existingplaylistimportdialog.o: moc_existingplaylistimportdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_existingplaylistimportdialog.o moc_existingplaylistimportdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

